### ISSUE TITLE
Shipping checklist for systemd infra overhaul

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#107]
The infrastructure overhaul in deconst/deploy#38 will take some care to :shipit:. Running Ansible on the existing hosts won't work because:
- It changes the names of server groups and load balancers because it implements #99 along the way.
- I've fiddled with the names of the systemd units that we're creating and managing, which means that we'd end up with both the old and new ones colliding unless I did a lot of tedious, error-prone, manual clean-up work.

Instead, I'm going to ship this in true immutable-infrastructure fashion, by spinning up brand-new hosts with the fancy new configuration and :hocho: the old ones. Here's the checklist:
- [x] Update the drc production playbook repository. Modify its `credentials.yml` to include the new keys.
- [x] Edit the server metadata of the existing deconst cluster to remove the `deconst-worker` Ansible group.
- [x] Rename the existing load balancers to follow the new naming pattern.
- [x] Run the new playbook on the production account. This will launch a brand-new cluster and new load balancer set.
- [x] Poke around the new cluster to ensure that everything is present and accounted for.
- [x] Drain connections from the old load balancer nodes, then delete them.
- [x] Delete the old cluster.
- [x] Stash the new version of `credentials.yml` in the usual place.

**Comment by smashwilson** [comment]
I'm glad I tried this out on staging first! The original hosts were in a group called "deconst-worker", which Ansible happily did a bunch of conflicting stuff to, anyway. There were also a few peekaboo issues that only cropped up once I launched multiple pods per host, and the pulls script was actually still broken.

I've got a [quick script](https://gist.github.com/smashwilson/4a3380546058bcec79d6) that I hashed out to punt the existing hosts to one side so I can provision the new hosts without interference. This should only be necessary for this upgrade; changing the deployment won't catch the old deployment's hosts because the group name is different.

I'm re-launching a cluster the old way right now so I can verify that these instructions work, beginning to end, without setting anything on fire by mistake.

**Comment by smashwilson** [comment]
Didn't quite get this done today. I'm running through the steps with staging and just did the `/etc/hosts` step.

**Comment by smashwilson** [comment]
For my own sanity, duplicating the checklist for **staging**:
- [x] Update the drc staging playbook repository. Modify its `credentials.yml` to include the new keys.
- [x] Edit the server metadata of the existing deconst cluster to remove the `deconst-worker` Ansible group.
- [x] Rename the existing load balancers to follow the new naming pattern.
- [x] Run the new playbook on the staging account. This will launch a brand-new cluster and new load balancer set.
- [x] Edit `/etc/hosts` and poke around the new cluster to ensure that everything is present and accounted for.
- [x] Drain connections from the old load balancer nodes, then delete them.
- [x] Delete the old cluster.
- [x] Stash the new version of `credentials.yml` in the usual place.

**Comment by smashwilson** [comment]
http://deconst.devsupport.me/ is now served by the new infrastructure. :sparkles:
