### ISSUE TITLE
Pull request builder

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#7]
To give content authors a way to share the results of unpublished (pushed, but not merged) work, I want to have a place where the built content of intermediate commits is available at a shareable link, in context with the rest of the hosted site. This will also make it easier for drive-by contributors to see their work rendered without having to fuss with the client.

My intention is for this to eliminate the need for a staging server.

_Implementation_

For any commit pushed to a pull request in a content repository, invoke the appropriate preparer on that version of the content in Strider (#1). Configure the preparer to use a content ID base unique to this build and to submit content to a dedicated content service running on the build host (#10).

Manipulate the content mapping used by a presenter running on the build host to mount the build-specific content ID prefix at a build-specific subpath. Hoist the mappings for the rest of the site beneath the same subpath. Do the same for the template routes. (It may be easier to use a custom subdomain?)

Configure the build-host content service to proxy any content IDs that are not found to the "real" content service CLB. That'll let you see the work in context.

Make a comment on the originating pull request that contains a link to the build content.

_Roadmap_
#### content-service
- [x] deconst/content-service#68
- [x] deconst/content-service#69
- [x] deconst/content-service#74
- [x] deconst/content-service#77
- [x] deconst/content-service#79
- [x] deconst/content-service#82
#### presenter
- [x] deconst/presenter#97
- [x] deconst/presenter#101
- [x] deconst/presenter#102
- [x] deconst/presenter#103
- [x] deconst/presenter#105
- [x] deconst/presenter#106
- [x] deconst/presenter#107
#### strider-deconst-content
- [x] deconst/strider-deconst-content#10
#### strider-deconst-control
- [x] deconst/strider-deconst-control#15
- [x] deconst/strider-deconst-control#14. Not directly related to pull request builds, but I want to be sure I've addressed this before the next time I recreate the Strider builds.
- [x] deconst/strider-deconst-control#18
#### services
- [x] deconst/services#19
- [x] deconst/services#20
#### deploy
- [x] deconst/deploy#99
- [x] deconst/deploy#102
- [x] :shipit:
  - [x] deconst.horse
  - [x] Nexus
  - [x] rackerlabs/nexus-control#363
#### deconst-docs
- [x] deconst/deconst-docs#224
- [x] deconst/deconst-docs#228
- [x] deconst/deconst-docs#223

**Comment by smashwilson** [comment]
When it's possible, I think it would be better to publish the result of merging the current ref into master rather than just the current ref. If the merge isn't clean, we could fall back to doing the current ref as-is.

**Comment by smashwilson** [comment]
/cc @catlook

I've written this up to start thinking about the way I'd like to implement this, and I want to make sure that I understand what you actually need! I probably won't get to this until we ship search (management priorities and all that) but I want to have a place for some early discussion. A few questions I have to get us started:

_Do you need the links to show the results of the build from a specific commit, or should it follow the work done on a branch?_

For example, say you're working in a branch called `add-more-cats` and you push it to GitHub and open a pull request. The pull request builder will be triggered and comment with a link to the rendered content at that point. But, if you later make additional commits on the `add-more-cats` branch and push those, should the _original_ link now show your _new_ work, or should it still show the original work and a new comment with a new link show the new work?

I can see uses for both. I could also implement both, but it might be confusing explaining which link is which.

_Should I build the content exactly as it is on the branch, or should I do a local merge against master first?_

There are CI systems for code that do both of these, and both are perfectly valid. Building the content exactly as it is on the branch makes it easier to understand what's going on; building the content after doing a local merge into "master" gives you a more accurate picture of what it'll really look like in production after you click the "merge" button.

I'm inclined to say "exactly as it is on the branch" but I'm curious what you'd prefer.

_Does the rendered content need to be private somehow?_

This would only really make sense when we're building from private repositories; otherwise anyone could just look at your source anyway. It would also be a lot more work to do this! We don't really have the concept of authentication anywhere in deconst yet. But I'm curious to hear if it's something that's necessary for the pull request builds or not.

**Comment by smashwilson** [comment]
/cc @j12y @steveortiz 

Naturally this will help the KC authoring process too :smile:

**Comment by smashwilson** [comment]
For those watching: I've updated the description :point_up: with a final countdown of the work that needs to happen to ship this. It's in sight!

/cc @meker12

**Comment by meker12** [comment]
:8ball:

**Comment by smashwilson** [comment]
Correction: I _had_ it written up all nicely, but then I think I commented while I was previewing it rather than updating the description and lost it all. This is a lot sparser on detail but it'll at least show progress!

**Comment by smashwilson** [comment]
Need to be sure to have a `robots.txt` that denies everything pretty strongly so Staging doesn't get crawled by Google.

**Comment by smashwilson** [comment]
It's alive!

![screen shot 2016-03-14 at 3 17 36 pm](https://cloud.githubusercontent.com/assets/17565/13756849/3d930bc8-e9f8-11e5-9d74-54004dcb32dd.jpeg)

**Comment by smashwilson** [comment]
I expect follow-on issues and edge cases to follow, but it looks like we're in business. Marking this as complete.

**Comment by meker12** [comment]
@smashwilson  If you have an existing PR, is there a way to make the PR build to staging?

**Comment by smashwilson** [comment]
> If you have an existing PR, is there a way to make the PR build to staging?

Hmm, it doesn't look like it. ([strider-github](https://github.com/Strider-CD/strider-github) is where Strider's GitHub provider is documented, by the way.)

You might be able to trigger a build by closing and re-opening the PR, but I haven't tried it.
