### ISSUE TITLE
Create a dedicated "meta" repository for organization-level issues and milestones

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#85]
- [ ] Create the "meta" repository.
- [ ] Write a quick README to explain why it's there.
- [ ] Migrate issues from this project to that one. Here's a batch issue mover that make help: https://github.com/IQAndreas/github-issues-import
- [ ] Make notes in the README of other repository in this organization to link to the org-level issue list.

/cc @rgbkrk

**Comment by annegentle** [comment]
I'd be happy with this - already getting confused about where to put a CSS issue for example.

**Comment by smashwilson** [comment]
Oh, this is for platform stuff - like extra fields that we need to collection, crashes and bugs, architecture changes, things like that. If the fix is a code change to deconst itself, the meta repo would be where it belongs.

Issues about _content_ changes probably belong on the specific content repository where the change should be made. Issues about assets like JavaScript, CSS, images, or fonts belong on the control repository for the deconst site you're talking about: in our case, [this one](https://github.com/rackerlabs/nexus-control).

**Comment by smashwilson** [comment]
Rather than doing this, I'm contemplating just re-opening issues on all of the deconst repositories. It turns out there actually _is_ [a consolidated view of all issues and pull requests across the org](https://github.com/orgs/deconst/dashboard) which I hadn't seen before, although you can only access it if you belong to the org.

The biggest thing we'd lose, in my opinion, is the ability to organize work by milestone. We're not following those particularly rigorously anyway though, and if we still need it we can work something out with labels instead.

It would also reignite confusion about which issue belongs on which repository, but we already have confusion between there, nexus-control, and the content repositories anyway. There will always be a certain amount of triage and shuffling.

@kenperkins, @ktbartholomew: any opinions?

**Comment by smashwilson** [comment]
Done a while ago - issues are open on all repos.
